<!DOCTYPE html>
<html lang="es">
<head>
    
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta charset="utf-8">
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/administrador/css/style.css');?>
    
    <!--start: Javascript -->
      <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>-->
      <?php echo $this->headScript()?>
    <!--end: Javascript -->
    <!--[if IE]>
		<link rel="stylesheet" type="text/css" href="css/style_ie.css">
	<![endif]-->
</head>
<body>
    <!--start: Header -->
	<?php echo $this->render("header.phtml");//cargamos el header ?>
    <!--end: Header -->
    <!--start: Sections -->
	<div class="container wrapper container-max-wrapper">
            <?php echo $this->render('menu-header.phtml');?>
            <div class="wrapper_body">
                <div class="row-fluid">
                   <?php echo $this->render('menu-left.phtml');?> 
                    <section class="span8 article_margin">
                        <div class="separador"></div>
                        
                    	<article>
                            <?php if(!empty($this->alert)):?>
                            <div class="alert alert_lila">
                                <?php echo $this->alert;?>
                                <button type="button" class="close" data-dismiss="alert"><i class="icon-close-alert"></i></button>
                            </div>
                            <?php endif;?>
                            <?php echo $this->layout()->content;//cargamos el contenido ?>
                        </article>
                    </section>
                </div>
            </div>
        </div>
    <!--end: Sections-->
    <!--start: Footer -->
        <?php echo $this->render("footer.phtml");//cargamos el footer ?>
    <!--end: Footer -->
    <?php echo $this->layout()->jquery?>
</body>
</html>