            <!--Start:Wrapper Header-->
            <div class="wrapper_header">
            	<div class="row-fluid">
                	<div class="span4">
                    	<div class="avatar_body">
                    	<div class="avatar">
                        	<ul>
                                                                                                                                                                                                                    
                                    <li> <a href="<?php echo $this->layout()->ruta?>admin/usuario/editavatar/id/<?php echo $this->layout()->id?>" class="fancybox fancybox.iframe"><img src="<?php echo $this->baseUrl?>/timthumb.php?src=files/img/avatar/<?php echo $this->layout()->avatar?>&a=t&w=56&h=56" width="56" height="56" class="img-circle"></a></li>
                                <li class="bienvenida"><?php echo $this->layout()->welcome?> </li>
                            </ul>                                
                        </div>
                        </div>
                    </div>
                    <div class="span8">
                        <div class="icons_sections">
                            <ul>
                                <li> <a href="<?php echo $this->baseUrl?>/admin/menu"><i class="icon-section-menus"></i></a> <br>Secciones</li>
                                <li> <a href="<?php echo $this->baseUrl?>/admin/entrada"><i class="icon-section-content"></i></a> <br>Contenidos</li>
                                <li><a href="<?php echo $this->baseUrl?>/admin/documento"><i class="icon-section-docs"></i><br></a>Documentos</li>
                                <li><a href="<?php echo $this->baseUrl?>/admin/imagen"> <i class="icon-section-img"></i><br></a>Imágenes</li>
                                <li><a href="<?php echo $this->baseUrl?>/admin/usuario"><i class="icon-section-users"></i><br></a>Usuarios</li>
                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!--end:Wrapper Header-->