                    <aside class="span4">
                    	<div class="col-menu">
                        	<div class="colmenu_header"><ul><li></li></ul></div>
                            <div class="colmenu_selector">
                                <select onchange="MM_jumpMenu('parent',this,0)">
                                    <option value="#">Menu opciones...</option>
                                    <option value="#">UTILIDADES</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/imagen/index">––- Subir Imágenes</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/documento/index">––- Subir Documentos</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/galeria/index">––- Crear Galerías</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/usuario/">––- Gestión Usuarios</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/corporativa/editar/id/1">––- Datos de Empresa</option>
                                    <option value="#">CONTENIDOS</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/usuario/listado">–-- Listar Usuarios</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/entrada/listado">–-- Listar Entradas</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/imagen/listado">–-- Listar Imágenes</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/galeria/listado">–-- Listar Galerías</option>
                                    <option value="<?php echo $this->baseUrl ?>/admin/corporativa/editar/id/1">–-- Datos de Empresa</option>
                                </select>
							
                            </div>
                            <div class="colmenu_cos hidden-phone">
                                    <ul class="nav">
                                        <li class="nav-header">
                                            <i class="icon-utilitys"></i> Utilidades
                                        </li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/imagen/index"> <i class="icon-upload-img-lt"></i> Subir imágenes </a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/documento/index"> <i class="icon-upload-doc"></i> Subir documentos</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/galeria/index"> <i class="icon-create-gallery"></i> Crear galerías</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/usuario/"><i class="icon-users-lt"></i> Gestión Usuarios</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/corporativa/editar/id/1"><i class="icon-corp-list"></i>  Datos de Empresa</a></li>
                                        <li class="nav-header">  
                                            <i class="icon-contents"></i> Contenidos
                                        </li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/usuario/listado"><i class="icon-user-list"></i> Listar Usuarios</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/entrada/listado"><i class="icon-news-list"></i> Listar Entradas</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/imagen/listado"><i class="icon-img-list"></i> Listar Imágenes</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/documento/listado"><i class="icon-upload-doc"></i> Listar Documentos</a></li>
                                        <li><a href="<?php echo $this->baseUrl ?>/admin/galeria/listado"><i class="icon-gallery-list"></i> Listar Galerías</a></li>
                                    </ul>               
                            </div>
                        </div>
                    </aside>