<div class="separador"></div>
<div class="row-fluid">
    <div class="span1">
        <icon class="icon-menus"></icon>
    </div>
    <div class="span11">
        <div class="article">
            
                <?php echo $this->form ?>
                                        <?php if(count($this->listMenus) > 0):?>
                                        <div class="separador"></div>
                                        <div class="accordion" id="accordion">
                                                <?php 
                                                    $i = 0;    
                                                        foreach($this->listMenus as $menu): 
                                                        $i++
                                                ?>        
                                            <!-- start:1-->
                                            <div class="accordion-group">
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $i;?>">

                                                </a>
                                                                            <div class="widget_list_users_cos">
                                                                                <div class="span12">
                                                                                    <span>Menú: </span><h2><?php echo stripslashes($menu->getTitol());?></h2>
                                                                                    <div class="rigth">
                                                                                        <div class="separador"></div>                                                                                       
                                                                                        <a href="<?php echo $this->baseUrl ?>/admin/menu/editarmenu/id/<?php echo $menu->getId()?>" id="edita<?php echo $i?>" rel="tooltip" title="Editar"><i class="icon-btn-edit-gris-fort"></i></a>
                                                                                        <?php if ($menu->getPublicar()==0):?>
                                                                                            <a href="<?php echo $this->baseUrl ?>/admin/menu/publicacio/id/<?php echo $menu->getId() ?>/page/<?php echo $this->paginator->getCurrentPageNumber();?>/val/1" id="publica<?php echo $i?>" rel="tooltip" title="Publicar"><i class="icon-btn-private-gris-fort"></i></a>
                                                                                        <?php else:?>
                                                                                            <a href="<?php echo $this->baseUrl ?>/admin/menu/publicacio/id/<?php echo $menu->getId() ?>/page/<?php echo $this->paginator->getCurrentPageNumber();?>/val/0" id="publica<?php echo $i?>" rel="tooltip" title="Despublicar"><i class="icon-btn-public-gris-fort"></i></a>
                                                                                        <?php endif;?>
                                                                                        <a href="<?php echo $this->baseUrl ?>/admin/menu/eliminar/id/<?php echo $menu->getId() ?>/page/<?php echo $this->paginator->getCurrentPageNumber();?>" id="borra<?php echo $i?>" rel="tooltip" title="Eliminar" onClick='return confirm("¿Estás seguro que quiere borrar este menú y sus submenús dependientes?")'><i class="icon-btn-close-gris-fort"></i></a>
                                                                                    </div>                            
                                                                                </div>
                                                                            </div>                                            
                                                                            <div class="clearfix"></div>
                                            </div>
                                            <div id="collapse<?php echo $i;?>" class="accordion-body collapse" style="height: 0px; ">
                                                <div class="accordion-inner">
                                                                            <div class="content_subSeccions">
                                                                                
                                                                                <?php 
                                                                                    $n = 0;   
                                                                                    foreach($menu->getSubMenus() as $subMenu): 
                                                                                        $n++;
                                                                                        ?>  
                                                                                
                                                                                    <div class="fields_subSeccions">
                                                                                        Submenú: <span><?php echo stripslashes($subMenu->getTitol());?></span>
                                                                                        <div class="rigth">
                                                                                            <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'menu','action'=>'editarsubmenu')).'/sub/'.$subMenu->getId();?>" id="editaLt<?php echo $i.$n?>" title="Editar" class="fancybox fancybox.iframe"><i class="icon-btn-edit-gris-lt"></i></a>
                                                                                            <?php if($subMenu->getPublicar()==1):?>
                                                                                            <a href="<?php echo $this->baseUrl ?>/admin/menu/publicacio/id/<?php echo $subMenu->getId();?>/val/0" id="publicaLt<?php echo $i.$n?>" rel="tooltip" title="Despublicar"><i class="icon-btn-public-lt"></i></a>
                                                                                            <?php else:?>
                                                                                            <a href="<?php echo $this->baseUrl ?>/admin/menu/publicacio/id/<?php echo $subMenu->getId();?>/val/1" id="publicaLt<?php echo $i.$n?>" rel="tooltip" title="Publicar"><i class="icon-btn-private-lt"></i></a>
                                                                                            <?php endif;?>
                                                                                            <a href="<?php echo $this->baseUrl ?>/admin/menu/eliminar/id/<?php echo $subMenu->getId();?>" id="borraLt<?php echo $i.$n?>" rel="tooltip" title="Eliminar" onClick='return confirm("¿Estás seguro que quiere borrar este submenú?")'><i class="icon-btn-close-lt"></i></a>
                                                                                        </div>
                                                                                    </div>
                                                                                <?php endforeach;?>
                                                                                        <div class="article_footer">
                                                                                        <ul>
                                                                                            <li class="span4">
                                                                                                <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'menu','action'=>'indexsubmenu')).'/id/'.$menu->getId();?>" class="fancybox fancybox.iframe">
                                                                                                        <button class=" btn-block btn_crear" type="submit">
                                                                                                                <i class="icon-btn-crear"></i>Crear Submenú
                                                                                                        </button>
                                                                                                </a>
                                                                                            </li>
                                                                                            <li class="span3 offset5"></li>
                                                                                        </ul>
                                                                                        <div class="clearfix"></div>
                                                                                </div>                         
                                                                            </div>
                                                </div>
                                            </div>
                                            </div>
                                            <!-- end:1-->                                        
                                            <?php endForeach;?> 
                                        </div>
                                        <?php endif;?>  
                                        <div class="article_footer">
                                            <div class="pagination pagination-right">
                                                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>                                        
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>  
        </div>
    </div>
</div>