                        <div class="separador"></div>
                        <article>
                        	<div class="row-fluid">
                            	<div class="span1">
                                    <icon class="icon-upload-docs"></icon>
                                </div>
                                <div class="span11">
                                    <div class="article">   
                                        <div style="padding:18px;">                                   
                                            <?php echo $this->form?>
                                        </div>                                                                                
                                    </div>
                                </div>
                            </div>
                        </article>

