                        <div class="separador"></div>
                        <article>
                        	<div class="row-fluid">
                            	<div class="span1">
                                    <icon class="icon-img"></icon>
                                </div>
                                <div class="span11">
                                    <div class="article">   
                                        <div style="padding:18px;">
                                                <form action="<?php echo $this->baseUrl ?>/admin/imagen/guardar/" class="dropzone" id="myDrop"></form>
                                                <div class="alert alert-info">Haz clic en las imágenes para escogerlas.</div>
                                        </div>                                       
                                        <div class="article_cos">
                                            <div id="lista_img">
                                                <ul class="thumbnails">  
                                                	<!-- Start:foreach-->    
                                                <?php if(count($this->listImagenes) > 0): ?>    
                                                    <?php 
                                                        $i = 0;
                                                            foreach($this->listImagenes as $imagen):
                                                            $i++;
                                                     ?>                                                        
                                                    <li class="clsCheckBox span3">
                                                    	<img src="<?php echo $this->baseUrl ?>/files/img/<?php echo $imagen->getRuta();?>" alt="tip" >                                                        
                                                        <p><?php echo $this->neteja->limitaNomImg($imagen->getRuta());?></p>  
                                                        <div class="widget_img_footer">
                                                                <a href="<?php echo $this->baseUrl ?>/files/img/<?php echo $imagen->getRuta();?>" class="imgs" rel="tip" title="<b>Título: </b> <?php echo $imagen->getTitol();?> <b>Fecha: </b><?php echo $imagen->getData()->format('d.m.Y');?>"><i class="icon-btn-expand-img"></i></a>
                                                        	<a href="#"><i class="icon-btn-close-lt"></i></a>
                                                        </div>   
                                                        <div class="clearfix"></div>                                         
                                                    </li>
                                                    <?php endforeach;?>
                                                    <!--End: foreach-->
                                                    <?php else:?>
                                                    <p>Lo sentimos, no hay  <strong>imágenes</strong> en el sistema</p>
                                                <?php endif;?>    
                                                </ul>
                                            </div>
                                            <div class="botonera_upload">
                                                    <form action="<?php echo $this->baseUrl ?>/admin/imagen/guardar/id/<?php echo $this->galId;?>" id="formulario" method="post" name="formulario">
                                                        <input id="variable" name="variable" type="hidden" />                                                  
                                                        <div class="row-fluid">    
                                                            <div class="span6 offset6"> 
                                                                <button class=" btn-block btn_public" type="submit" id="btnSnorkel">
                                                                    <i class="icon-btn-public"></i> Crear galeria
                                                                </button>
                                                            </div>             
                                                        </div>
                                                        <div class="clearfix"></div>
                                                    </form>
                                            </div>
                                        </div>
                                        <div class="article_footer">
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>

