
                                            <div class="separador"></div>
                                               <form class="form-horizontal" action="<?php print $this->escape($this->element->getAction()); ?>" method="<?php print $this->escape($this->element->getMethod()); ?>" enctype="multipart/form-data">
                                                    <?//php print $this->element->id;?>
                                                    <?//php print $this->element->MAX_FILE_SIZE;?>
                                                    <div class="control-group">
                                                        <div class="span12 code"> Escoge un archivo jpg o png que no supere los 200 kb </div>                                                                                                           
                                                        <input type="file" title="Busca tu imágen aquí" name="avatar" class="btn-primary">
                                                    </div>                           
                                                    <div class="article_footer">
                                                        <ul>
                                                            <li class="span3 offset9">
                                                            	<button class="btn-block btn_public" id="aceptar" type="submit">
                                                                	<i class="icon-btn-crear"></i> Subir imágen
                                                                </button>
                                                            </li>
                                                            
                                                        </ul>
                                                    </div>  
                                                   <div class="clearfix"></div>  
                                               </form> 