                                	<div class="widget_form">
                                                <form class="form-horizontal" action="<?php print $this->escape($this->element->getAction()); ?>" method="<?php print $this->escape($this->element->getMethod()); ?>">
                                                    <?php print $this->element->id;?>
                                                    <?//php print $this->element->data;?>
                                                    <?php print $this->element->update;?>
                                                    <?php print $this->element->publicar;?>
                                                    <?php print $this->element->predet;?>
                                                    <?php print $this->element->menuParent;?>
                                                    <div class="control-group">               
                                                            <div class="span6">
                                                                <?php print $this->element->idioma;?>
                                                            </div>
                                                            <div class="span3 offset3">
                                                                <?php print $this->element->orden;?>
                                                                <span class="code"><b>*</b> Orden por defecto</span>
                                                            </div>
                                                    </div>
                                                    <div class="control-group">
                                                    	<div class="span6">								
                                                               
                                                            <?php print $this->element->zona;?>
                                                        </div>  
                                                    	<div class="span6">								
                                                            <?php print $this->element->entrada;?>     
                                                      </div>                                                 
                                                    </div> 
                                                    <div class="control-group">
                                                            <?php print $this->element->titulo;?>
                                                    </div>
                                                  	<div class="control-group">
                                                            <?php print $this->element->url;?>
                                                            
                                                            <span class="code"><b>*</b> Ej.: www.loremipsum.com sin escribir <em>http://</em></span>
                                                        </div>
                                                    
                                                  <div class="article_footer">
                                                        <ul>
                                                            <li class="span3 offset6">
                                                            	<button class=" btn-block btn_public" type="submit">
                                                                	<i class="icon-btn-public"></i> <?php print $this->element->crear->getLabel(); ?>
                                                                </button>
                                                            </li>
                                                            <li class="span3">
                                                                <button class=" btn-block btn_cancel" type="reset">
                                                                    <i class="icon-btn-delete"></i> <?php print $this->element->cancelar->getLabel(); ?>
                                                                </button>
                                                            </li>
                                                        </ul>
                                                   </div>  
                                                   <div class="clearfix"></div>  
                                               </form>
                                        </div>